### PR TITLE
Build test

### LINKED ISSUE #24: Can't run from commandline
Tests pass--which include running `Seqr.main()` without error--but I get an exception if I try running directly from the commandline. This suggests to me that there is a problem with the `pom` file.
I tried removing `<scope> test </scope>` [here](https://github.com/DCGenomics/seqr/blob/26a09883e858a8fec2a225a558302ee4489c392c/pom.xml#L55-L61) but that did not help.

### PR DESCRIPTION
**Pull request by averagehat**
Closes #24

### CODE REVIEW

**Comment by lianyi** [comment]
```
 @Test
+//    public void testArgParse() {
+//        String[] args = {"search",  "testdata/data/test.fasta", "--db", "testdata/solr/"};
+//        Seqr.main(args);
+//
+//        }
```

Looks this was commented out, Perhaps this test failed on travis?

**Comment by averagehat** [comment]
@lianyi, The test actually passes, however I removed it because Travis was taking longer than ten minutes to build. Unfortunately that did not work. 

Travis runs fine if I do not specify before_script or `script` or anything like that, but if I do, I get errors like `org.apache.solr.common.SolrException: No such core: sequence`, like [here](https://travis-ci.org/NCBI-Hackathons/seqr/builds/78102493). 

I am not sure what is wrong, but I think there is a difference between what travis does by default and what I am doing, or else maybe travis is trying to run things concurrently when it shouldn't.

**Comment by lianyi** [comment]
I see, I suspect it's the default heap size for the maven test. Perhaps the heap size can be configured  to 1G in travis?  Or perhaps just skip this testing unit in travis...

**Comment by averagehat** [comment]
Yay, finally, I was able to get this working, although I don't quite understand The depth of the problem. 
Now the robot tests I added (which test the build after the `jar` is created to avoid problems like #24) are run within the maven `test` phase, using www.github.com/robotframework/MavenPlugin

So this is ready to merge, you can review if you like, @lianyi, or go ahead and merge.

**Comment by lianyi** [comment]
I'm working on the merging and it looks great!  Good job on getting "robotframework" works!

**Pull request merged**
