### PR TITLE
Index

### LINKED ISSUE #29: index command
Not sure if i was looking at the right place.

**seqr/src/main/java/gov/nih/nlm/ncbi/seqr/solr/SeqrController.java**

```
   public SolrDocumentList index(String proteinSequence) {
        return null;
    }
```

Was this index method overridden/implemented somewhere that able to index the JSON and/or FASTA files?  I saw samples in unit testing that we able to index josn files though.

### PR DESCRIPTION
**Pull request by averagehat**
Closes #29 
This is working on my machine but I will add tests before it's ready for merging
- [ ] fix how ID is set
- [ ] add tests, inc. with multi-file/entry indexing
- [ ] test/fix JSON file loading
- [ ] try with big file
- [ ] refactor so indexing lives outside of Seqr.handleCommand

### CODE REVIEW

**Comment by lianyi** [comment]
@averagehat Sounds good to you to merge this index branch? Bo is making FASTA indexer and after seeing the diff, It seems best to merge this branch first to avoid minimum code conflict.

**Comment by averagehat** [comment]
Yes let me see if I can get the build to pass or at least working on my machine. This branch may be a bit outdated from my local code. 

Is he creating the fasta indexer as a Solr process/request handler? It would be great if he could make a pull request (or at least issue) even if he is not done, that would help with visibility and not duplicating work.

**Comment by lianyi** [comment]
@averagehat Gr8!  Sounds a good plan!

**Comment by averagehat** [comment]
You/Bo may want to check out this in the meantime, I think it includes a fasta indexer #44

**Comment by averagehat** [comment]
The main purpose of this PR was to unify JSON and FASTA indexing. #45 has a different but working approach to that so I am going to close this and open up a new PR

**Pull request closed without merging**
